### ISSUE TITLE
1.16.5 - Tuinity Error

### ISSUE THREAD

**Issue by XC012** [apavarino/Deadchest#2]
Sometimes i get this error:
[DeadChest] Task #145 for DeadChest v4.4.0 generated an exception
java.lang.IllegalStateException: null
at java.util.ArrayList$Itr.remove(ArrayList.java:874) ~[?:1.8.0_282]
at me.crylonz.DeadChest$1.run(DeadChest.java:296) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1475) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

I dont know why and when it just randomly show in console. If you need some more info feel free to ask me, I dont know If there is some format for Error reports.

**Comment by apavarino** [comment]
Thanks for the report !

That will be fix in the version 4.5.0

I'm working on template for error report. it's not ready yet :)

**Comment by apavarino** [comment]
Fix in 4.5.0
