### ISSUE TITLE
EnableWorldGuardDetection

### ISSUE THREAD

**Issue by SladeGit** [apavarino/Deadchest#49]
**Context**
- DeadChest 
- latest
- 1.19.2
- PaperMC latest

**Describe the bug**
If "EnableWorldGuardDetection: true"

### **Error:**
Error occurred while enabling DeadChest v4.12.0 (Is it up to date?)
java.lang.IllegalStateException: New flags cannot be registered at this time
        at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:60) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
        at me.crylonz.WorldGuardSoftDependenciesChecker.load(WorldGuardSoftDependenciesChecker.java:25) ~[DeadChest-4.12.0.jar:?]
        at me.crylonz.DeadChest.onEnable(DeadChest.java:77) ~[DeadChest-4.12.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-161]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-161]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

newest worldguard verion

**Comment by apavarino** [comment]
Thanks for the report ! This issue is fixed on 4.12.1. Available soon on Bukkit
