### ISSUE TITLE
unable to list all deadchest on a server command

### ISSUE THREAD

**Issue by Cvar1984** [apavarino/Deadchest#65]
DeadChest-4.16.1.jar
CraftBukkit version 3869-Spigot-d2eba2c-78796c9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

unable to list all deadchest on a server command
`dc list all` return
```
17:06:25] [Server thread/INFO]: [DeadChest] List of all dead chests:
[17:06:25] [Server thread/WARN]: Unexpected exception while parsing console command "dc list all"
org.bukkit.command.CommandException: Unhandled exception executing command 'dc' in plugin DeadChest
 v4.16.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1
-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.2
0.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877) ~[spig
ot-1.20.1-R0.1-SNAPSHOT.jar:3869-Spigot-d2eba2c-78796c9]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:862) 
~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3869-Spigot-d2eba2c-78796c9]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:412) ~[spigot-1.2
0.1-R0.1-SNAPSHOT.jar:3869-Spigot-d2eba2c-78796c9]
```

**Comment by apavarino** [comment]
Cannot reproduce on `4.17.0`
